# Ejecutar con: --spring.profiles.active=postgres   (antes: CREATE DATABASE smartdelivery;)
spring.datasource.url=jdbc:postgresql://localhost:5432/smartdelivery
spring.datasource.username=postgres
spring.datasource.password=tu_clave
spring.h2.console.enabled=false
