# Ejecutar con: --spring.profiles.active=mysql   (antes: CREATE DATABASE smartdelivery;)
spring.datasource.url=jdbc:mysql://localhost:3306/smartdelivery?useSSL=false&serverTimezone=America/Guatemala&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=tu_clave
spring.h2.console.enabled=false
